services:
  dev:
    image: portfolio-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 5173:5173
    container_name: portfolio-dev
